### ISSUE TITLE
Spring 2017 feeds list Cleaning 

### ISSUE THREAD

**Issue by karlcow** [webcompat/planet.webcompat.com#7]
Some blogs are not active, broken. Some are new.

## To remove

* https://blogs.msdn.microsoft.com/ieinternals/
* http://pipes.yahoo.com/pipes/pipe.run?_id=4c225a8277e401f5daabb4252e1ced9c&_render=rss There are gone. The intent emails still exist, but the pipes service doesn't. If I remember there is a twitter account broadcasting those.

## To add

* https://blogs.windows.com/msedgedev/tag/interoperability/feed/

@denschub @adamopenweb @miketaylr @zoepage @wisniewskit @MDTsai other suggestions are welcome.

**Comment by denschub** [comment]
We could add http://schub.io/blog/feeds/mozilla.xml, which is a feed for my blog posts tagged with "mozilla".

**Comment by miketaylr** [comment]
> The intent emails still exist, but the pipes service doesn't. If I remember there is a twitter account broadcasting those.

https://twitter.com/intenttoship

**Comment by karlcow** [comment]
Ah thanks @miketaylr. This will require a bit more engineering since twitter axed the feeds a couple of years ago. 😒 I will fix the others. Thanks.
